export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited transaction with zero fees",
    description: "Get acess to our exclusive app that allows you to send unlimited transaction without getting charged any fees",
    buttonLabel: "Get started",
    imgStart: false,
    img: require("../../images/Hero.svg"),
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
}